part of client.src.messages.message;

/// A control message represents messages communicated by the application and
/// are emitted by changes within the state of the application. Control messages
/// are unidireciton in that they only display to a single user and do not
/// traverse the network.
class ControlMessage extends Message {
  bool viewed = true;

  ControlMessage(String messageText) {
    body = messageText;
  }

  @override
  Map marshal() => {
        // Becuase control messages are generated by the application they do not
        // traverse the network so calls to marshal return no value.
      };
}
